spring:
  application:
    name: QuickReserve
    server:
      address: 0.0.0.0
      port: 8080
  datasource:
    url: jdbc:postgresql://localhost:5432/QuickReserve
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true